apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels: 
      app: firstapp
  template:
      metadata:
        name: firstpod
        labels:
          app: firstapp
        spec:
          containers:
            name: firstcontainer
            image: nginx
            ports:
              - containerPort: 80