apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: firstreplica
spec:
  replicas: 4
  selector:
    matchExpressions:
      - {key: app, operator: IN, values: [firstpod]}
  template:
    metadata: 
     name: firstpod
    labels:
      app: firstapp
    spec:
      containers:
        - name: firstcontainer
          image: nginx
          ports:
            - containerPort: 80

        - name: secondcontsiner
          image: httpd
          ports:
            - containerPort: 80
