apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: firstreplica
spec:
  replicas: 4
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [firstapp]}
  template:
    metadata: 
     name: firstpod
     labels:
      app: firstapp
    spec:
      containers:
        - name: secondcontsiner
          image: httpd:2.4
          ports:
            - containerPort: 80
